[package]
name = "zkID"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bn254 = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-serialize = "0.5.0"
ark-std = "0.5.0"
chrono = { version = "0.4.44", features = ["serde"] }
ed25519-dalek = "2.2.0"
elliptic-curve = "0.13.8"
rand = "0.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.11.0"
unit-conversions = "0.1.16"
num-bigint = "0.4"
num-prime = "0.4"
blake2b_simd = "1"
num-modular = { version = "0.6", features = ["num-bigint", "num-integer", "num-traits"] }
num-integer = "0.1"
num-traits = "0.2"

